In [1]:
import numpy as np

# Практическое задание по теме "Введение в линейную алгебру"
https://docs.google.com/document/d/1DirQtAXL8-vwD4eaogN89pW2h3xN3ZtO25sDIs-wwqU/edit#heading=h.gjdgxs

## 5.1 (на листочке)
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.

In [5]:
E = np.identity(5)
print(E)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
print(np.linalg.inv(5*E))

[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]


## 5.2. (на листочке)
Вычислите определитель:
\begin{pmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9
\end{pmatrix}

In [11]:
A5_2 = np.array([[1,2,3], [4,0,6],[7,8,9]])
np.linalg.det(A5_2)

59.999999999999986

## 5.3.

### 1. Вычислите матрицу, обратную данной:
\begin{pmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9
\end{pmatrix}

In [9]:
A5_3 = np.array([[1,2,3], [4,0,6],[7,8,9]])
np.linalg.inv(A5_3)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

### 2. Приведите пример матрицы 4х4, ранг которой равен 1.

## 5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

In [17]:
a = np.array([1,5])
b = np.array([2,8])

np.dot(a, b)

42

## 5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


In [13]:
a = np.array([1,5,0])
b = np.array([2,8,7])
c = np.array([7,1.5,3])
print(c * np.dot(a, b))

[294.  63. 126.]
