In [2]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.linalg import lu

# Практическое задание по теме "Системы линейных алгебраических уравнений":
https://docs.google.com/document/d/1n_aHRBF6McVWJUM1YMnqqJD6HocVxjRJM2e7cAajHnc/edit

## 1. Решите линейную систему:
<img src="https://github.com/koryagin2006/GB_Course_Introduction_to_Higher_Mathematics/blob/master/img/les_7_1.png?raw=1" alt="Drawing" style="width: 300px;">

In [0]:
A1 = np.array([[1,2,3],[4,0,6],[7,8,9]])
B1 = np.array([12,2,1])

Решение

In [3]:
X1 = np.linalg.solve(A1,B1)

for i in range(3):
    print(f'x_{i+1} = {round(X1[i], 5)}')
# Сделал с округлением для читаемости

x_1 = -9.2
x_2 = 0.9
x_3 = 6.46667


## 2. Найдите псевдорешение:
```
x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15
```

In [0]:
A2 = np.array([[1,2,-1],
              [3,-4,0],
              [8,-5,2],
              [2,0,-5],
              [11,4,-7]])
B2 = np.array([1,7,12,7,12])

Решение

In [5]:
X2 = np.linalg.lstsq(A2,B2, rcond=None)
X2

(array([ 0.96772642, -1.11719341, -0.89887891]),
 array([2.77449966]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [6]:
# Проверка
np.around(np.dot(A2, [X2[0][0], X2[0][1], X2[0][2]]), decimals=2)

array([-0.37,  7.37, 11.53,  6.43, 12.47])

## 3. Сколько решений имеет линейная система:
<img src="https://github.com/koryagin2006/GB_Course_Introduction_to_Higher_Mathematics/blob/master/img/les_7_2.png?raw=1" alt="Drawing" style="width: 300px;">

In [0]:
A3 = np.arange(1,10).reshape(3,3)
B3 = np.array([[12,2,1]])

Решение

In [8]:
C3 = np.concatenate((A3,B3.T), axis=1)

if np.linalg.matrix_rank(A3, 0.0001) == np.linalg.matrix_rank(C3, 0.0001):
  print('СЛАУ совместна')
else:
  print('СЛАУ несовместна - не имеет решений')
C3

СЛАУ несовместна - не имеет решений


array([[ 1,  2,  3, 12],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  1]])

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее.


In [9]:
# изменим
A3_2 = np.array([[1,3,3],[4,5,6],[7,8,10]])
B3_2 = np.array([[2,2,1]])

C3_2 = np.concatenate((A3_2,B3_2.T), axis=1)
print('Ранг А = ',np.linalg.matrix_rank(A3_2, 0.0001)) 
print('Ранг С = ',np.linalg.matrix_rank(C3_2, 0.0001))
print('')
C3_2

Ранг А =  3
Ранг С =  3



array([[ 1,  3,  3,  2],
       [ 4,  5,  6,  2],
       [ 7,  8, 10,  1]])

In [14]:
print(np.linalg.det(A3_2))

# np.linalg.solve(A3_2,B3_2)

-0.9999999999999964


## 4. Вычислите LU-разложение матрицы:
<img src="https://github.com/koryagin2006/GB_Course_Introduction_to_Higher_Mathematics/blob/master/img/les_7_3.png?raw=1" alt="Drawing" style="width: 100px;">

После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [30]:
A4 = np.array([[1,2,3],
               [2,16,21],
               [4,28,73]])

In [31]:
P, L, U = lu(A4)

np.dot(L,U)

array([[ 4., 28., 73.],
       [ 1.,  2.,  3.],
       [ 2., 16., 21.]])

## 5. Найдите нормальное псевдорешение недоопределенной системы:
```
x + 2y – z = 1
8x – 5y + 2z = 12
```
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 

In [33]:
A5 = np.array([[1,2,-1],[8,-5,2]])
B5 = np.array([1,12])

Решение

In [38]:
def Q(x,y,z):
    return (x**2 + y**2 + z**22)
Q(3,4,6)

131621703842267161

In [41]:
from pylab import *
from mpl_toolkits.mplot3d import Axes3D

минимум нормы решение

In [36]:
np.linalg.lstsq(A5,B5, rcond=None)[0]

array([ 1.38191882, -0.18081181,  0.0202952 ])

## 6. Найдите одно из псевдорешений вырожденной системы:
<img src="https://github.com/koryagin2006/GB_Course_Introduction_to_Higher_Mathematics/blob/master/img/les_7_4.png?raw=1" alt="Drawing" style="width: 300px;">
Попробуйте также отыскать и нормальное псевдорешение.