In [1]:
import numpy as np

# Практическое задание по теме "Введение в линейную алгебру"
https://docs.google.com/document/d/1DirQtAXL8-vwD4eaogN89pW2h3xN3ZtO25sDIs-wwqU/edit#heading=h.gjdgxs

## 5.1 (на листочке)
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.

In [14]:
E = np.identity(5)
print(E)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 5.2. (на листочке)
Вычислите определитель:
\begin{pmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9
\end{pmatrix}

In [11]:
A5_2 = np.array([[1,2,3], [4,0,6],[7,8,9]])
np.linalg.det(A5_2)

59.999999999999986

## 5.3.

### 1. Вычислите матрицу, обратную данной:
\begin{pmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9
\end{pmatrix}

In [9]:
A5_3 = np.array([[1,2,3], [4,0,6],[7,8,9]])
np.linalg.inv(A5_3)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

### 2. Приведите пример матрицы 4х4, ранг которой равен 1.

## 5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)


In [12]:
A5_4 = np.array([1,5]) * np.array([2,8])
A5_4

array([ 2, 40])

## 5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 
